// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9wrgLOLZhTHdb9T8LZi_GrLo1ee46VtI',
    appId: '1:134053036585:web:da632401d840f79dbd5238',
    messagingSenderId: '134053036585',
    projectId: 'scholaria-shop',
    authDomain: 'scholaria-shop.firebaseapp.com',
    storageBucket: 'scholaria-shop.firebasestorage.app',
    measurementId: 'G-B4SEEYL486',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ-dCX5L6cCW1XtJtybercTOOnSPVSVuo',
    appId: '1:134053036585:android:5738f3f3eab6f1f9bd5238',
    messagingSenderId: '134053036585',
    projectId: 'scholaria-shop',
    storageBucket: 'scholaria-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdu-bV_UMIJ20RWvB6GntvtqUSXbKOuuo',
    appId: '1:134053036585:ios:61ff9f34cdabafedbd5238',
    messagingSenderId: '134053036585',
    projectId: 'scholaria-shop',
    storageBucket: 'scholaria-shop.firebasestorage.app',
    iosBundleId: 'com.example.scholariaShopV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdu-bV_UMIJ20RWvB6GntvtqUSXbKOuuo',
    appId: '1:134053036585:ios:61ff9f34cdabafedbd5238',
    messagingSenderId: '134053036585',
    projectId: 'scholaria-shop',
    storageBucket: 'scholaria-shop.firebasestorage.app',
    iosBundleId: 'com.example.scholariaShopV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9wrgLOLZhTHdb9T8LZi_GrLo1ee46VtI',
    appId: '1:134053036585:web:607071f0f93b305abd5238',
    messagingSenderId: '134053036585',
    projectId: 'scholaria-shop',
    authDomain: 'scholaria-shop.firebaseapp.com',
    storageBucket: 'scholaria-shop.firebasestorage.app',
    measurementId: 'G-GPT539NPTJ',
  );
}
